### ISSUE TITLE
Scrobble doesn't work on open.spotify.com

### ISSUE THREAD

**Issue by eldonzo** [david-sabata/web-scrobbler#1273]
Some days ago play.spotify.com started to redirect to open.spotify.com, so the web player is totally new.
The Chrome extension says the site is supported, but it doesn't recognize the songs played.

**Comment by sdjasfijsdfisjdf** [comment]
Same problem here, also tried the unpacked version mentioned in #1269 with no positiv result. Eventhough Spotify (open) has appeared at the connectors list... but it's still showing "play some music to get started" when music is actually playing in Spotify.

**Comment by alexesprit** [comment]
[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by alexesprit** [comment]
The issue actually is fixed in #1272. Have you tried to use the extension with this patch applied?

**Comment by eldonzo** [comment]
I'll just wait for the extension to update with the fix, thanks for letting know.

**Comment by sdjasfijsdfisjdf** [comment]
This is the log when entering spotify:
https://pastebin.com/WyVzCXVW

Those are the errors i found further up the console:
https://pastebin.com/10dYgMVi

But somehow i don't understand what I have to do with the source code in #1272. Can you explain?

**Comment by alexesprit** [comment]
The changes made in #1272 are in master, so you can use [this](https://github.com/david-sabata/web-scrobbler#unpacked-extension) howto to install the fixed extension.

**Comment by sdjasfijsdfisjdf** [comment]
Sorry, I still don't get it... So you are saying that the changes are already in the app? As mentioned before in my first comment I did install the unpacked extension with no positive result in scrobbling. 

Also one day later chrome browser crashed and deleted all bookmarks and appdata from my harddrive so I've installed the version from the chrome store again.

**Comment by musthabe** [comment]
I unpacked the newest extension manually within the Extensions menu. 
The version is 1.62.2.
open.spotify.com is not scrobbling, even though it says supported site, it isn't recognizing the song being played.

**Comment by sdjasfijsdfisjdf** [comment]
@musthabe thanks for your help, now i've got it!
